version: '3.7'

services:
  postgresql:
    image: postgres:alpine
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'root']
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
     - 5432:5432

volumes:
  postgresql_data: